### ISSUE TITLE
Balance tweaks for the SSG

### ISSUE THREAD

**Issue by Dox778** [Dox778/WhoDunIt-Reloaded#4]
Some people find it unfair that it's capable of two-shot killing innocents and the vote results are in favor of tweaking it to address it.
One potential idea is to just lower the damage of the ssg to make it impossible to bring a fully healed innocent down to 0 health.

**Comment by Teribearo** [comment]
At the moment, the breathing effect is disabled, but not removed.

**Comment by Teribearo** [comment]
https://github.com/Dox778/WhoDunIt-Reloaded/commit/7f2d308876f653c2c378a16c45dc15506548b61a

**Comment by Teribearo** [comment]
Done https://github.com/Dox778/WhoDunIt-Reloaded/commit/39c0ef0eef6389de43889e31f360b4ef2a1d9358
